### PR TITLE
Consider a factory's entire ancestry

### PR DESCRIPTION
**Pull request by jonstorer**
Consider a factory's entire lineage for attributes.

I used chai's `expect` interface because `should` breaks down when running assertions against undefined or null values. I'd be willing to change it to use `should` if you'd like.

``` javascript

var define = require('seed-forge').define;
var build  = require('seed-forge').build;

// define User
define('User', User)
  .set('email', function (n) { return 'user' + n + '@example.com'; })
  .set('name', 'Fred')
  .set('admin', false)
  .set('disabled', false);

// define Admin
define('Admin', User).extend('User')
  .set('admin', true);

// define DisabledAdmin
define('DisabledAdmin', User).extend('Admin')
  .set('disabled', true);

console.log(attributes('User'));
// { email: 'user1@example.com', name: 'Fred', admin: false, disabled: false }

console.log(attributes('Admin'));
// { email: 'user2@example.com', name: 'Fred', admin: true, disabled: false }

// include attributes from all ancestors  
console.log(attributes('DisabledAdmin'));
// { email: 'user3@example.com', name: 'Fred', admin: true, disabled: true }

```

### CODE REVIEW

**Comment by jonstorer** [comment]
@vesln I didn't realize that pushing my master was going to change this PR, Can you look at these commits separately and I'll try to open separate pull requests for each

**Comment by jonstorer** [comment]
@vesln Hey man, I'd really like to get this into your project. Can you tell me either way if that's going to happen? If not, I'll happily keep our fork and move on. Just let me know!

**Comment by vesln** [comment]
Sure, do you want to become the maintainer of the project, I'm not using it much these days?

**Comment by vesln** [comment]
Happy to provide full github + npm access

**Comment by jonstorer** [comment]
@vesln That would be great!

**Comment by vesln** [comment]
Just gave you full github access. I'd need to know your npm username in order to add you there as well

**Comment by vesln** [comment]
My only ask would be to use semver as it is intended, because I have clients relying on this project and I wouldn't want to break their projects. Other than that, feel free to go wild :)

**Comment by jonstorer** [comment]
my npm user name is `yonafin`. I will bump a minor version since this does change things a bit.

**Comment by jonstorer** [comment]
@vesln Have you reviewed the changes? Both commits? (I didn't mean for this one PR to include both commits).  I'm concerned with how factories inherit hooks... by just copying. Do you have any other suggestions?

**Pull request closed without merging**
